lab_1/urls.py
from django.urls import re_path
from .views import index
#tambahan
from django.conf import settings
from django.conf.urls.static import static


#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab_2/urls.py
from django.urls import path
from .views import index

#url for app, add your URL Configuration

urlpatterns = [
#TODO Implement this
]

lab_4/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views
app_name = 'lab_4'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.mainHome, name="mainHome"),
    path('profil/', views.profile, name="myProfile"),
    path('register/', views.register, name="registerHere"),
    path('add_schedule/', views.schedule_form, name="addSchedule"),
    path('schedule_list/', views.schedule_list, name="scheduleList"),
    path('display/', views.display_form, name="display"), 
    path('schedule_remove/', views.remove_schedule, name="schedule_remove")
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lab_6/urls.py
from django.conf.urls import url
from .views import index

app_name = "lab_6"
urlpatterns = [
	url(r'^$', index, name='index'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import lab_6.urls as lab_6
import lab_4.urls as lab_4
# from lab_1.views import index as index_lab1
#from lab_4.views import mainHome as home



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab_4/', include(lab_4,namespace='lab_4')),
    url(r'^lab_6/', include(lab_6,namespace='lab_6')),
]

lab_1/models.py
from django.db import models

# Create your models here.

lab_2/models.py
from django.db import models

# Create your models here.

lab_4/models.py
from django.db import models
from django.utils import timezone
from datetime import date, datetime

class Schedule(models.Model):
	hour_min = models.TimeField(auto_now = False, auto_now_add = False)
	activity = models.CharField(max_length=27)
	place = models.CharField(max_length=27)
	category = models.CharField(max_length=27)

lab_6/models.py
from django.db import models

# Create your models here.

lab_4/forms.py
from django import forms
import datetime
from .models import Schedule

class ScheduleForm(forms.Form):
	hour_min = forms.TimeField(label="Hour : Min", widget = forms.TimeInput(attrs={'type' : 'time'}))
	activity = forms.CharField(label="Activity")
	place = forms.CharField(label="Location")
	category = forms.CharField(label="Category")


	

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
# Enter your name here
mhs_name = 'Gusti Ngurah Yama Adi Putra' # TODO Implement this
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(1999,10,23) #TODO Implement this, format (Year, Month, Date)
npm = '1706979253' # TODO Implement this
kuliah = "University of Indonesia"
hobi = "Ngoding"
deskripsi = "Seorang mahasiswa yang berharap bisa lulus dengan predikat cumlaude"

# Create your views here.
def index(request):
    response = {'name': mhs_name, 'age': calculate_age(birth_date.year), 'npm': npm,
    			'kuliah': kuliah, 'hobi': hobi, 'deskripsi': deskripsi}
    return render(request, 'index_lab1.html', response)

def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0

lab_2/views.py
from django.shortcuts import render
from lab_1.views import mhs_name, birth_date

#TODO Implement
#Create a content paragraph for your landing page:
landing_page_content = ''

def index(request):
    response = {'name': mhs_name, 'content': landing_page_content}
    return render(request, 'index_lab2.html', response)

lab_4/views.py
from django.shortcuts import render
from .forms import ScheduleForm
from .models import Schedule
from django.http import HttpResponseRedirect

response = {}

# Test
def mainHome(request):
 	return render(request,'pepew3.html')

def profile(request):
	return render(request, 'pepew3_2.html')

def register(request):
	return render(request, 'pepew3_3.html')

def schedule_form(request):
	response['form'] = ScheduleForm
	return render(request, "ScheduleForm.html", response)

def display_form(request):	
	form = ScheduleForm(request.POST or None)
	if(request.method == "POST" and form.is_valid()):
		response['hour_min'] = request.POST.get('hour_min')
		response['activity'] = request.POST.get('activity')
		response['place'] = request.POST.get('place')
		response['category'] = request.POST.get('category')

		Schedules = Schedule(hour_min=response['hour_min'],
		 					 activity=response['activity'], place=response['place'], category=response['category'])

		
		Schedules.save()

		response['form'] = form

		Schedules = Schedule.objects.all()
		response['Schedules'] = Schedules
		return render(request, 'ScheduleList.html' , response)
	
	else:
		return HttpResponseRedirect('/')

def schedule_list(request):
	Schedules = Schedule.objects.all()
	response['Schedules'] = Schedules
	return render(request, 'ScheduleList.html' , response)

def remove_schedule(request):
	Schedules = Schedule.objects.all().delete()
	return render(request, 'ScheduleList.html', {})

lab_6/views.py
from django.shortcuts import render

def index(request):
 	return render(request,'landing_page.html')

lab_1/templates/index_lab1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<center>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>My Life</title>
    <style type="text/css">
    .responsive{
        max-width: : 100%;
        width: auto;
    }
    @media screen and (max-width: 800px){
        .responsive{
            width: 90%
        }
    }

    @media only screen and (max-width:620px) {
     /* For mobile phones: */
        .responsive{
            width:100%;
        }
    }

    @media only screen and (max-width:400px) {
     /* For mobile phones: */
        .responsive{
            width:100%;
        }
    }

    </style>
</head>

<style>
h1{
	color:#cc2900;
	font-family:Libre Baskerville;
	font-size: 350%;
    border-top: 3px dotted #e67300;
    border-right: 3px solid #e67300;
    border-bottom: 3px dotted #e67300;
    border-left: 3px solid #e67300;
}
h2{
    color:#c2c2a3;
    font-family:montserrat;
    font-size: 250%;
}
article{
	font-family:domine;
	color:#e0e0d1;
	font-size: 120%;
}
img{
	border-radius: 8px;
}
</style>

<body background="https://newevolutiondesigns.com/images/freebies/black-iphone-wallpaper-10.jpg">
<!-- <img src="{% static './4x4.jpg' %}" alt="My image", height = 400> -->
    <h1> My Info </h1>
    <h2>
    	Gusti Ngurah Yama Adi Putra<article style="font-size: 50%;">1706979253</article><hr>
    </h2>
    <img src ="http://www.about.tarung2017.com/foto/312.jpg" alt="orang ganteng", height=300>
    <article>
    	Study at University of Indonesia
    	</br> seorang dengan hobi Ngoding <br></br> Seorang mahasiswa yang berharap bisa lulus dengan predikat cumlaude dan berguna bagi sesama. </br>
	</article>


	<h1> My Friends </h1>
	<h2>
    	</br>Rafif Taris<article style="font-size: 50%;">1706979436</article><hr>
    </h2>
    <img src ="http://www.about.tarung2017.com/foto/329.jpg" alt="rafif", height=300>
    <article>
    	Study at University of Indonesia
    	</br> seorang dengan hobi Mendengarkan Musik, Main Game, Membaca Novel <br></br> Saya suka mendengarkan musik terutama genre K-Pop dan EDM. Saya masuk Fasilkom UI karena saya ingin mendalami sistem keamanan komputer. Menjadi programmer web adalah salah satu langkah menuju impian saya. See you on top guys! </br>
	</article>

	<h2>
    	</br>Raihansyah Attallah Andrian <article style="font-size: 50%;">1706040196</article><hr>
    </h2>
    <img src ="http://www.about.tarung2017.com/foto/330.jpg" alt="dean", height=300>
    <article>
    	Study at University of Indonesia
    	</br> seorang dengan hobi bermain game dan main musik<br></br> Sangat tidak ambiz. </br>
	</article>

<!--  -->
</body>
</center>
</html>

lab_2/templates/description_lab2addon.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<body style="background-color: aqua">
    <h3 style="text-align: center">Hi all, This is my complete biodata</h3>
    <table align="center" style="text-align: center">
        {% for bio in bio_dict %}
            <tr>
                <td class="subject">{{ bio.subject }}</td>
                <td class="value">{{ bio.value }}</td>
            </tr>
        {% endfor %}
    </table>
    <br><br>
</body>

</html>

lab_2/templates/index_lab2.html
{% extends "base.html" %}
{% block content %}
<style>
    .center_screen {
        position: absolute;
        width: 500px;
        height: 50px;
        top: 50%;
        left: 50%;
        margin-left: -250px; /* margin is -0.5 * dimension */
        margin-top: -25px;
    }
</style>
<div class="center_screen">
    <p class="status" id="test">Hello, this is {{ name }}. {{ content }}.</p>
</div>
{% endblock %}

lab_4/templates/ScheduleForm.html
{% extends 'starter.html' %}


{% block content %}
{% load static %}

<div style="background-color:#FFD089; text-align: center">
	<h1><strong class="judulDiv"> Create Schedule Here </strong></h1>
		<section>
			<div class = "my-auto">
				<div>
					<form id='form' method="POST" action="{% url 'lab_4:display' %}" >
						{% csrf_token %}
						{% for field in form %}
						<div class = "form-group">
							<label class = "text"> {{ field.label }} <br> {{field}}
							</label>
						</div>
						{% endfor %}
						<input id="submit" type="submit" class="btn btn-lg btn-primary" value="Create"><br>
					</form>
				</div>
			</div>
		</section>
</div>
{% endblock %}

lab_4/templates/ScheduleList.html
{% extends 'starter.html' %}



{% block content %}
{% load static %}
<div style="background-color:#FFD089; text-align: center;height: 45vw">
	<br> 
	<h1><strong class="judulDiv">List of Schedule </strong></h1>

	<table class="table">
		{% if Schedules %}
			<thead>
				<th>Date</th>
				<th>Hour</th>
				<th>Activity</th>
				<th>Location</th>
				<th>Category</th>
			</thead>

			<tbody>
				{% for s in Schedules %}
					<tr class = "success">
						<td>{{s.day}} , {{s.date}}</td>
						<td>{{s.hour_min}}</td>
						<td>{{s.activity}}</td>
						<td>{{s.place}}</td>
						<td>{{s.category}}</td>
					</tr>
				{% endfor %}
			</tbody>

		{% else %}
			<h2 class = "text">### Empty ###</h2>
		{% endif %}
	</table>

	<button type="button" class="btn btn-danger" onclick="location.href='{% url 'lab_4:schedule_remove' %}' "> Remove Schedule</button>

</div>

{% endblock %}

lab_4/templates/pepew3.html
{% extends 'starter.html' %}

{% block content %}
{% load static %}

	<div class = "foto">
		<article><br></article>
		<div id = "textBoxFoto">
			<article class="text" style="font-size:3.2vw;margin-left:8vw;color:#683B12">
				A Journey<br>From Someone<br><br>&emsp;&emsp;Whose Life<br>&emsp;&emsp;In The Middle Of<br>&emsp;&emsp;The Universe
			</article>
		</div>
		<br><br><br><br>
	</div>
	<hr class = "garis">


	<div class = "bot-nav">
		<div class="text bot-nav1"> 
			<article>
				<center>
					<strong style="font-size:2vw">
						Hai, I’m Yama
					</strong>
					<br>I’m a Programmer whose love art, perfectionist, and you<br><a href="profil/" class="btn btn-primary btn-sm active" role="button" aria-pressed="true" style="margin:1vw;box-shadow:2px 2px 2px grey;font-size:1.2vw">Learn more</a>
				</center>
			</article>
		</div>

		<div class="text bot-nav2"> 
			<article>
				<center>
					<strong style="font-size:2vw">
						Multi Discipline
					</strong>
					<br>Beside coding, there are organitation, art, and sport too<br><a href="profil/" class="btn btn-primary btn-sm active" role="button" aria-pressed="true" style="margin:1vw;box-shadow:2px 2px 2px grey;font-size:1.2vw">Learn more</a>
				</center>
			</article>
		</div>

		<div class="text bot-nav3"> 
			<article>
				<center>
					<strong style="font-size:2vw">
						Explorer
					</strong>
					<br>our world is very-very big, but these are my interest<br><a href="profil/" class="btn btn-primary btn-sm active" role="button" aria-pressed="true" style="margin:1vw;box-shadow:2px 2px 2px grey;font-size:1.2vw">Learn more</a>
				</center>
			</article>
		</div>

		<div class="text bot-nav4"> 
			<article>
				<center>
					<strong style="font-size:2vw">
						Interested?
					</strong>
					<br>Wanna know more? what you waiting for? Got in touch!<br><a href="register/" class="btn btn-primary btn-sm active" role="button" aria-pressed="true" style="margin:1vw;box-shadow:2px 2px 2px grey;font-size:1.2vw">Learn more</a>
				</center>
			</article>
		</div>
	</div>
{% endblock %}

lab_4/templates/pepew3_2.html
{% extends 'starter.html' %}

{% block content %}
{% load static %}

	<div style="background-color:#FFD089">
		<img src="https://scontent-sin6-2.xx.fbcdn.net/v/t1.0-9/42096564_2248932005134775_9146408516422991872_n.jpg?_nc_cat=100&oh=aed0da5a16ba852ce6c5d204ab054d6e&oe=5C2087FE" alt="foto uci" class="logo" style="width:20vw;border-radius: 50%;margin:3vw;margin-top:1.6vw;">
		<center>
			<article class="text" style="margin-left:29vw;margin-right:10vw;"><br>
				<strong class="judulDiv">
					This is Me
				</strong><br><br>
				<article style="font-size:2vw;">
					Hai, I’m Yama
				</article>
				<article style="font-size:1.5vw;">
					Currently a computer science student undergraduate in University of Indonesia. Perfectionist and ambitious are two things that are very attached to me. I spent my spare time for refreshing my soul, such as playing games, sport, or watch some film.<br><br><br>
				</article>
			</article>
		</center>
	</div><hr class = "garis">

	<div class="skills">
		<br><center>
			<strong class="judulDiv">
				My Skills
			</strong>
		</center>

		<div class="text program"> 
			<center>
				<article>
					&emsp;<img src="https://www.shareicon.net/data/512x512/2016/01/13/702849_code_512x512.png" alt="code"style="width:8vw;"><br>&emsp;
					<strong style="font-size:1.8vw">
						Programming
					</strong> 
					<br>&emsp;C++<br>&emsp;Python<br>&emsp;Java<br>
				</article>
			</center>
		</div>

		<div class="text sport"> 
			<center>
				<article>
					<strong style="font-size:1.8vw">
						Sport
					</strong>
					<br>Badminton<br>Taekwondo<br>E-Sport<br>
					<img src="https://mbtskoudsalg.com/images/shoe-silhouette-png-8.png" alt="sport shoes" style="width:10vw;margin-top:2vw;">
				</article>
			</center>
		</div>

		<div class="text organitation"> 
			<center>
				<article>
					<img src="https://mbtskoudsalg.com/images/png-background-creator.png" style="width:8vw;">
					<strong style="font-size:1.8vw">
						Organitation
					</strong>
					<br>DPM Fasilkom UI<br>Ristek Fasilkom UI<br>A Lot of Events<br>
				</article>
			</center>
		</div>

		<div class="text editing"> 
			<center>
				<article>
					<strong style="font-size:1.8vw">
						Editing
					</strong>
					<br>Photoshop<br>Sony Vegas<br>
				<img src="https://vignette.wikia.nocookie.net/lostpedia/images/e/e0/Clapperboard.png/revision/latest?cb=20080328214142" style="width:7.5vw;margin-top:1.5vw;">
			</article>
		</center>
		</div>

		<div class="text character"> 
			<center>
				<article>
					<img src="https://www.freeiconspng.com/uploads/muscle-icon-1.png" style="width:10vw;">
					<strong style="font-size:1.8vw">
						Character
					</strong>
					<br>Ambitious<br>Adaptive<br>
				</article>
			</center>
		</div>
	</div>
	<hr class = "garis">


	<div style="background-color:#FFEEB1;height:39vw;">
		<br><center>
			<strong class="judulDiv">
				Interest in
			</strong>
		</center>

		<div class="text" style="float:left;font-size:1.8vw;margin:1.2vw;margin-top:0vw;margin-left:5vw;width:45vw;text-align: right;">
			<strong style="font-size:3vw;color:#905050;">
				<u text-align: right;>Formal</u>&ensp;
			</strong>
			<article style="margin:1vw; margin-left:0vw;">
				<strong style="font-size:2vw;">
					Problem Solve
				</strong>
				<br>I’d like to solve a problem that people can’t </br>
			</article>

			<article style="margin:1vw;">
				<strong style="font-size:2vw; margin-left:0vw;">
				UI/UX Designer
				</strong>
				<br>Study PPW in University of Indonesia, make me want to be a UI/UX Designer</br>
			</article> 
				
			<article style="margin:1vw; margin-left:0vw;">	
				<strong style="font-size:2vw;">
					Game Development
				</strong>
				<br>beside like to play e-sport, I also like to make it</br>
			</article>
		</div>

		<div class="text" style="float:left;font-size:1.8vw;margin:1.2vw;margin-top:0vw;width:45vw;text-align: left;">
			<strong style="font-size:3vw;color:#905050;">
				<u text-align: right;>Informal</u>
			</strong>
			<article style="margin:1vw; margin-left:0vw;">
				<strong style="font-size:2vw;">
					E-Sport
				</strong>
				<br>Playing game is the best refresing for me</br>
			</article>

			<article style="margin:1vw;">
				<strong style="font-size:2vw; margin-left:0vw;">
				Discover the Whole World
				</strong>
				<br>Our world absolutly big, but nothing is immposible until God call you to come back home</br>
			</article> 
				
			<article style="margin:1vw; margin-left:0vw;">	
				<strong style="font-size:2vw;">
					Nature and Ecosystem
				</strong>
				<br>Tree, bird, sea sore, mountain, and me...</br>
			</article>

		</div>
	</div>
	<hr class = "garis">

	<div style="background-color:#D56509;height:15vw;">
		<br><center>
			<strong class="judulDiv" style="font-size:3vw;line-height:3vw;">
				Find Me
			</strong>
		</center>
		<article>
			<img src="http://pngimg.com/uploads/email/email_PNG55.png" alt="email" style="width:3.5vw; margin-left:9.5vw;margin-top:3vw;">
			gustingurah.yama@gmail.com
			<img src="https://image.ibb.co/dnJjEz/line.png" alt="line" style="width:3.5vw; margin-left:5vw;margin-top:3vw;">
			@gnyap2310
			<img src="https://image.ibb.co/d4aaMe/ig.png" alt="ig" style="width:3.5vw; margin-left:5vw;margin-top:3vw;">
			@gustinyap
			<img src="https://preview.ibb.co/gHFxZz/phone.png" alt="phone" style="width:3.5vw; margin-left:5vw;margin-top:3vw;">
			083838718942
		</article>
	</div> 
{% endblock %}

lab_4/templates/pepew3_3.html
{% extends 'starter.html' %}

{% block content %}
{% load static %}

	<div id="registerBack">
		<article style="margin-left:36vw;padding-top:2.5vw;"><strong class="judulDiv">Register Here</strong></article>
		<form style="margin-left:5vw;margin-right:5vw;">
			<div class="form-group">
		    	<label for="name" class="text">Name</label>
		    	<input type="text" class="form-control" id="name" aria-describedby="nameHelp" placeholder="Enter Name">
		 	</div>
		 	<div class="form-group">
		    	<label for="bornDate" class="text">Born Date</label>
		    	<input type="date" class="form-control" id="bornDate" aria-describedby="dateHelp" placeholder="Enter Date">
		 	</div>
		 	<div class="form-group">
		    	<label for="email" class="text">Email Address</label>
		    	<input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
		    	<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
		    </div>
		 	<div class="form-group">
		    	<label for="username" class="text">Username</label>
		    	<input type="text" class="form-control" id="username" placeholder="Enter Username">
		  	</div>
		  	<div class="form-group">
					<label for="Password" class="text">Password</label>
					<input type="password" class="form-control" id="Password" placeholder="Password">
				</div>
				<div class="form-group">
					<label for="PasswordConf" class="text">Password Confirmation</label>
					<input type="password" class="form-control" id="PasswordConf" placeholder="Password">
				</div>
				<a href="javascript:history.go(-1);" class="btn btn-primary btn-sm active" role="button" aria-pressed="true" style="box-shadow:2px 2px 2px grey;font-size:1.5vw;">Submit</a>
		</form>
	</div>
{% endblock %}

lab_4/templates/starter.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<title>My Journey</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static "css/pepew3.css" %}">
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Suravaram" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Habibi" rel="stylesheet">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
 
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>

<body>
	<div class="head">
		<img src=" https://scontent.fcgk10-1.fna.fbcdn.net/v/t1.0-9/41984447_2248979878463321_1292254070504947712_n.jpg?_nc_cat=0&oh=9f3e018ad91f8d33c6524fde8e2e0926&oe=5C2CAE40" alt="logo" class="logo">
		<article class="judulHeader">
			FRAMTIDEN
		</article>
		<article class="subJudulHeader">
			Gusti Ngurah Yama Adi Putra's Journey
		</article>
	</div>
	<hr class = "garis">

	<!-- NAVBAR -->
	<nav class="navbar navbar-expand-lg navbar-light">
		<a class="navbar-brand active" href="{% url 'lab_4:mainHome' %}"> <img src="https://vignette.wikia.nocookie.net/lionheart-tactics/images/9/9a/Home.png/revision/latest?cb=20150218040604&format=original" style="width:3vw;"><span class="sr-only">(current)</span></a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		  	<span class="navbar-toggler-icon"></span>
		</button>
	  
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
		  	<ul class="navbar-nav mr-auto">
				<li class="nav-item">
			  		<a class="nav-link" href="{% url 'lab_4:myProfile' %}">Profile</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'lab_4:registerHere' %}">Register</a>
			  	</li>
			  	<li class="nav-item">
					<a class="nav-link" href="{% url 'lab_4:addSchedule' %}">Add Schedule</a>
			  	</li>
			  	<li class="nav-item">
					<a class="nav-link" href="{% url 'lab_4:scheduleList' %}">My Schedule</a>
			  	</li>
		  	</ul>
		</div>
	</nav>
	{% block content %}
	{% endblock %}

</body>
</html>

lab_6/templates/landing_page.html
<!DOCTYPE html>
<html>
	<head>
		<title>TDDD</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	</head>

	<body>
		<center><h1> Hai, Apa kabar? </h1></center>
	</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<body style="background-color: lightgray">
    <div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/lab-2/">Home</a>
              </li>
              <li class="nav-item" >
                <a class="nav-link" href="/lab-2-addon/">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/lab-3/">Diary</a>
              </li>
            </ul>
          </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
{% block jquery %}
{% endblock %}
</html>